### ISSUE TITLE
Find out how multiple choice questions can be supported in the database

### ISSUE THREAD

**Issue by tmaregge** [Omjoa001/Web_Prosjekt#17]
Suggestion: Add a field to denote how many answers are correct. 
Ex: If this field is 2, the first 2 answers are the correct ones. 
This requires strict ordering of answers.

**Comment by Omjoa001** [comment]
We decided to add a numCorrect column which is an int with the amount of correct answers. The answers are then added to the table in order of correct answers first followed by the incorrect ones. This means that frontend has to randomize the order in which questions are showed, but keep track of their placement in the table.
